[package]
name = "producer-consumer"
version = "0.1.0"
rust-version = "1.65.0"
authors = ["Isi Bernoff"]
description = "A simple banking application with concurrent transaction execution"
edition = "2021"

[dependencies]